sudo: false
language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn run type
- yarn run lint
- yarn test
notifications:
  email:
    on_success: never
    on_failure: never
before_deploy: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: info@darwineducation.com
  api_key:
    secure: o2k5C8p131oIc1qM65tb/Kjubg4re7mO15tZPq1zlzcZM1FRNq8cKPCBXUIbZg8NsBB64tcHFt1SI6buTHJCq1AAQg7VNEd8497C7IUo8A23lbbsehySdCH3HqtAtiwchkuAEVsg8B6oG6uIbTxR/FqDduU/dx4CznC2SoMpypuWWMqpGIfsEKM9F2+4VnoEj964Z7YRVFC3a8d/TZ8/uODVwmlm+5iPM/CmUvAU3PNESpOd7ldC7OrOhsm0jTEZC1hfD+Cuj1B9GZhN+SgPHjxTQn+aIR9A0f74FaPDx86NLV3CC7J3XTz4rEwfNYHz7MDJ/Dsv4p0IgPVrr+inXEC/bDESa0aKqL+VHNJsEk44wOvFOjGcZWksP/CZied25d1HMzEaolJtQ7nVH15/233MG3zuVd6aeTYStcS5ezVs+oxP98Am6kXu9uLznhRkT10sbAXL09SxtLAj0ALBp2RGv7G1zVAEedeJ+o54HatgDGYOvxnTiNg04q+sqSzBMTOCYYlfbZQrevwDJzuK3DFJL+13PAvpzEwf2xmHEk++i6fl9ye1bZcs8A1P+lGr3HvENPix7vcYy8SQz9s7lXBT5Rd5NzzXcQSUNafksBbMtLNpIdv8L5wRWKArg7H24hr2NYubGvibPQPMFDCoBuyBmLgkMSWiMpk2Rd+XBfI=
  on:
    tags: true
    repo: darwin-education/resium
